id = "sealcode"
name = "Sealcode"
description = "The open source coding agent."
version = "1.15.3"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/mnmalali/sealcode"

[agent_servers.sealcode]
name = "Sealcode"
icon = "./icons/sealcode.svg"

[agent_servers.sealcode.targets.darwin-aarch64]
archive = "https://github.com/mnmalali/sealcode/releases/download/v1.15.3/sealcode-darwin-arm64.zip"
cmd = "./sealcode"
args = ["acp"]

[agent_servers.sealcode.targets.darwin-x86_64]
archive = "https://github.com/mnmalali/sealcode/releases/download/v1.15.3/sealcode-darwin-x64.zip"
cmd = "./sealcode"
args = ["acp"]

[agent_servers.sealcode.targets.linux-aarch64]
archive = "https://github.com/mnmalali/sealcode/releases/download/v1.15.3/sealcode-linux-arm64.tar.gz"
cmd = "./sealcode"
args = ["acp"]

[agent_servers.sealcode.targets.linux-x86_64]
archive = "https://github.com/mnmalali/sealcode/releases/download/v1.15.3/sealcode-linux-x64.tar.gz"
cmd = "./sealcode"
args = ["acp"]

[agent_servers.sealcode.targets.windows-x86_64]
archive = "https://github.com/mnmalali/sealcode/releases/download/v1.15.3/sealcode-windows-x64.zip"
cmd = "./sealcode.exe"
args = ["acp"]
