import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const SEALCODE_EXPERIMENTAL = truthy("SEALCODE_EXPERIMENTAL")
const copy = process.env["SEALCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  SEALCODE_AUTO_HEAP_SNAPSHOT: truthy("SEALCODE_AUTO_HEAP_SNAPSHOT"),
  SEALCODE_GIT_BASH_PATH: process.env["SEALCODE_GIT_BASH_PATH"],
  SEALCODE_CONFIG: process.env["SEALCODE_CONFIG"],
  SEALCODE_CONFIG_CONTENT: process.env["SEALCODE_CONFIG_CONTENT"],
  SEALCODE_DISABLE_AUTOUPDATE: truthy("SEALCODE_DISABLE_AUTOUPDATE"),
  SEALCODE_ALWAYS_NOTIFY_UPDATE: truthy("SEALCODE_ALWAYS_NOTIFY_UPDATE"),
  SEALCODE_DISABLE_PRUNE: truthy("SEALCODE_DISABLE_PRUNE"),
  SEALCODE_DISABLE_TERMINAL_TITLE: truthy("SEALCODE_DISABLE_TERMINAL_TITLE"),
  SEALCODE_SHOW_TTFD: truthy("SEALCODE_SHOW_TTFD"),
  SEALCODE_PERMISSION: process.env["SEALCODE_PERMISSION"],
  SEALCODE_DISABLE_AUTOCOMPACT: truthy("SEALCODE_DISABLE_AUTOCOMPACT"),
  SEALCODE_DISABLE_MODELS_FETCH: truthy("SEALCODE_DISABLE_MODELS_FETCH"),
  SEALCODE_DISABLE_MOUSE: truthy("SEALCODE_DISABLE_MOUSE"),
  SEALCODE_FAKE_VCS: process.env["SEALCODE_FAKE_VCS"],
  SEALCODE_SERVER_PASSWORD: process.env["SEALCODE_SERVER_PASSWORD"],
  SEALCODE_SERVER_USERNAME: process.env["SEALCODE_SERVER_USERNAME"],

  // Experimental
  SEALCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("SEALCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  SEALCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("SEALCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  SEALCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("SEALCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  SEALCODE_MODELS_URL: process.env["SEALCODE_MODELS_URL"],
  SEALCODE_MODELS_PATH: process.env["SEALCODE_MODELS_PATH"],
  SEALCODE_DB: process.env["SEALCODE_DB"],

  SEALCODE_WORKSPACE_ID: process.env["SEALCODE_WORKSPACE_ID"],
  SEALCODE_EXPERIMENTAL_WORKSPACES: SEALCODE_EXPERIMENTAL || truthy("SEALCODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get SEALCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("SEALCODE_DISABLE_PROJECT_CONFIG")
  },
  get SEALCODE_TUI_CONFIG() {
    return process.env["SEALCODE_TUI_CONFIG"]
  },
  get SEALCODE_CONFIG_DIR() {
    return process.env["SEALCODE_CONFIG_DIR"]
  },
  get SEALCODE_PURE() {
    return truthy("SEALCODE_PURE")
  },
  get SEALCODE_PLUGIN_META_FILE() {
    return process.env["SEALCODE_PLUGIN_META_FILE"]
  },
  get SEALCODE_CLIENT() {
    return process.env["SEALCODE_CLIENT"] ?? "cli"
  },
}
